version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 80:80
    links:
      - redis
    volumes:
      - /path-to-backend-here:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

