#!/bin/bash

[program:laravel]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work redis --sleep=3 --tries=3 --queue=accounts
autostart=true
autorestart=true
numprocs=8
redirect_stderr=true
stdout_logfile=/app/storage/logs/worker.log